spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/workout_db?auto"
    username: root
    password: hunjo0220@
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show_sql: true

